## 定义变量
variables:
  Tags: v1
  app: nginx
  Template: deploy_template.yaml
  web: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-deploy1

## 执行前动作
before_script:
  - sudo docker version

## 执行步骤
stages:
  - test
  - build
  - release

## 测试
test:
  stage: test
  only:
    - master
  script:
    - echo "------  test. ------"
  tags:
    - hub.jevic.io

## 构建应用
build:
  stage: build
  only:
    - master
  script:
    - uname -a
    - Image="$registry/$repo/$app:$Tags"
    - echo $Image
    #- sudo docker login -u "$USER" -p "$PASSWD" $registry
    #- sudo docker build --pull -t $Image .
    #- sudo docker push $Image
    #- sudo docker rmi -f $Image
    - /bin/sed -i "s#IMAGE#$Image#g" $Template > deployment.yaml
    - cat deployment.yaml
  tags:
    - hub.jevic.io

## deployment to kubernetes
release:
  stage: release
  only:
    - master
  script:
    - sh deploy.sh
    #- echo deploy.sh
  tags:
    - hub.jevic.io
