variables:
  Tags: v1

stages:
  - build
#  - release
# 构建镜像
build:
  stage: build
  script:
    - docker --version
    - uname -a
    - echo "$registry/$repo:$Tags"
    - docker login -u "$USER" -p "$PASSWD" $registry
#    - docker build --pull -t "$registry/$repo:$Tags" .
#    - docker push "$registry/$repo:$Tags"
#    - docker rmi -f "$registry/$repo:$Tags"
  tags:
    - devops
# 升级rancher服务
#release:
#  stage: release
#  script:
#    - sh update.sh $Webhook $repo
