## 定义变量
variables:
  Tags: v1
  app: nginx
  Template: deploy_template.yaml
  web: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-deploy1
image: jevic/app:v1

## 执行前动作
before_script:
  - sudo docker version

## 执行步骤
stages:
  - test
  - build

## 测试
test:
  stage: test
  only:
    - master
  script:
    - echo "------  test. ------"
    - echo ${CI_JOB_NAME}
    - echo ${CI_COMMIT_REF_NAME}
  tags:
    - hub.jevic.io

## 构建应用
build:
  stage: build
  only:
    - master
  script:
    - uname -a
    - Image="$registry/$repo/$app:$Tags"
    - echo $Image
  tags:
    - hub.jevic.io
