variables:
  Tags: v1
  app: nginx
  web: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-deploy1
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: demo-c
      template:
        metadata:
          labels:
            app: demo-c
        spec:
          containers:
          - name: demo-c
            image: jevic/demo:latest
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80

stages:
  - build
#  - release
# 构建镜像
build:
  stage: build
  script:
    - docker --version
    - uname -a
    - Image="$registry/$repo/$app:$Tags"
    - echo $Image
    - echo update.sh
#    - /bin/sh curl -X POST -H 'Content-Type: application/yaml' http://192.168.2.68:9090/api/v1/namespaces/default/pods -d "$(cat demo.yaml)"
#    - sudo docker login -u "$USER" -p "$PASSWD" $registry
#    - sudo docker build --pull -t $Image .
#    - sudo docker push $Image
#    - sudo docker rmi -f $Image
  tags:
    - hub.jevic.io

## deployment
#release:
#  stage: release
#  script:
#    - sh update.sh
