## 定义变量
variables:
  Tags: v2
  app: nginx
  web: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-deploy1
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: demo-c
      template:
        metadata:
          labels:
            app: demo-c
        spec:
          containers:
          - name: demo-c
            image: jevic/demo:latest
            imagePullPolicy: IfNotPresent
            ports:
            - containerPort: 80

## 执行前动作
before_script:
  - sudo docker version
  - sudo docker info
  - sudo docker login -u "$USER" -p "$PASSWD" $registry

## 执行步骤
stages:
  - test
  - build
  - release

## 测试
test:
  stage: test
  only:
    - master
  script:
    - echo "------  test. ------"
  tags:
    - hub.jevic.io

## 构建应用
build:
  stage: build
  only:
    - master
  script:
    - docker --version
    - uname -a
    - Image="$registry/$repo/$app:$Tags"
    - echo $Image
    - sudo docker build --pull -t $Image .
    - sudo docker push $Image
    - sudo docker rmi -f $Image
#    - sed -i \"s/IMAGE/$Image/g\" template_demo.yaml
  tags:
    - hub.jevic.io

## deployment to kubernetes
release:
  stage: release
  only:
    - master
  script:
    - sh update.sh
  tags:
    - hub.jevic.io
