variables:
  Tags: v1
  app: nginx

stages:
  - build
#  - release
# 构建镜像
build:
  stage: build
  script:
    - docker --version
    - uname -a
    - Image="$registry/$repo/$app:$Tags"
    - echo $Image
    - sudo docker login -u "$USER" -p "$PASSWD" $registry
#    - sudo docker build --pull -t "$registry/$repo:$Tags" .
#    - sudo docker push "$registry/$repo:$Tags"
#    - sudo docker rmi -f "$registry/$repo:$Tags"
  tags:
    - devops
# 升级rancher服务
#release:
#  stage: release
#  script:
#    - sh update.sh $Webhook $repo
